version: '3'
services:
  db:
    image: mysql
    ports:
      - "3301:3306"
    expose:
      - 3306
    environment:
      - MYSQL_ROOT_PASSWORD=sugudbpassword
      - MYSQL_DATABASE=sugu_db
    volumes:
      - ./sugu-db-data:/var/lib/mysql
    restart: always
    networks:
      - sugu-network
    
  app:
    depends_on:
      - db
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sugu-back
    environment:
      - PORT=5000
      - DATABASE_URL=mysql://root:sugudbpassword@db:3306/sugu_db
    ports:
      - '5000:5000'
    volumes:
      - ./uploads:/app/uploads
    networks:
      - sugu-network
    restart: unless-stopped
  

volumes:
  sugu-db-data:


networks:
  sugu-network:
    driver: bridge
