version: '3.9'

services:
  db:
    image: postgres:13
    container_name: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=adminpsql
      - POSTGRES_DB=sugu_db
    ports:
      - '5432:5432'
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - mynetwork

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sugu-back-dev
    environment:
      - PORT=5000
      - DATABASE_URL=postgresql://postgres:adminpsql@db:5432/sugu_db?schema=public
    ports:
      - '5000:5000'
    depends_on:
      - db
    volumes:
      - ./src:/app/src
      - ./uploads:/app/uploads
      - ./prisma:/app/prisma

    networks:
      - mynetwork

volumes:
  db-data:

networks:
  mynetwork:
    driver: bridge
# pgadmin:
#   image: dpage/pgadmin4
#   restart: always
#   container_name: nest-pgadmin4
#   environment:
#     - PGADMIN_DEFAULT_EMAIL=admin@admin.com
#     - PGADMIN_DEFAULT_PASSWORD=pgadmin4
#   ports:
#     - '5050:80'
#   depends_on:
#     - db
