apiVersion: v1
kind: Service
metadata:
  name: sugu-back-service
  namespace: sugu
  labels:
    app:  sugu-back-service
spec:
  selector:
    app: sugu-back-nestjs
  ports:
    - protocol: TCP
      targetPort: 5000
      port: 8080
  type: NodePort
