-- Création de la table si nécessaire (exemple)
-- CREATE TABLE "CategorieProduit" (
--     "id" SERIAL PRIMARY KEY,
--     "nom" VARCHAR(255) NOT NULL,
--     "description" TEXT
-- );

INSERT INTO CategorieProduit (nom, description)
VALUES
    ("Fruits", "Produits issus des vergers, très variés et colorés."),
    ("Légumes", "Produits du potager, riches en vitamines."),
    ("Boissons", "Liquides en tout genre : jus, sodas, etc."),
    ("Pâtisseries", "Viennoiseries et gâteaux sucrés."),
    ("Charcuterie", "Viandes préparées, saucissons, jambons."),
    ("Fromages", "Produits laitiers affinés de différentes régions."),
    ("Fruits de mer", "Crustacés, mollusques et poissons."),
    ("Épicerie", "Condiments, conserves et articles d'épicerie sèche."),
    ("Sauces", "Assaisonnements liquides pour accompagner les plats."),
    ("Produits bio", "Aliments issus de l'agriculture biologique."),
    ("Snacks", "En-cas, chips et barres salées ou sucrées."),
    ("Céréales", "Blé, avoine, riz, maïs, etc."),
    ("Produits surgelés", "Articles conservés à très basse température."),
    ("Confiseries", "Bonbons, chocolats et autres sucreries."),
    ("Plats cuisinés", "Plats prêts à consommer, réchauffables."),
    ("Biscuits", "Biscuiteries sucrées ou salées."),
    ("Végétarien", "Produits adaptés à un régime sans viande."),
    ("Vegan", "Aliments sans aucun produit d'origine animale."),
    ("Produits sans gluten", "Aliments adaptés aux intolérances au gluten."),
    ("Épices", "Herbes aromatiques et assaisonnements variés."),
    ("Produits laitiers", "Lait, yaourts, crèmes et desserts lactés."),
    ("Viandes", "Viandes fraîches de différentes espèces animales."),
    ("Poissons", "Poissons frais et produits de la mer."),
    ("Pains", "Différents types de pains et produits de boulangerie."),
    ("Produits diététiques", "Aliments adaptés à des régimes spécifiques."),
    ("Produits halal", "Aliments conformes aux règles alimentaires islamiques."),
    ("Produits casher", "Aliments conformes aux règles alimentaires juives."),
    ("Produits pour bébés", "Aliments spécialement conçus pour les nourrissons."),
    ("Produits de beauté", "Cosmétiques et produits de soin."),
    ("Produits d'entretien", "Articles pour le nettoyage et l'entretien de la maison."),
    ("Produits pour animaux", "Nourriture et accessoires pour animaux de compagnie."),
    ("Produits de saison", "Aliments disponibles selon les saisons."),
    ("Produits locaux", "Aliments produits localement."),
    ("Produits importés", "Aliments importés de différentes régions du monde."),
    ("Produits de luxe", "Articles haut de gamme et produits premium."),
    ("Produits en promotion", "Articles en promotion ou en solde."),
    ("Produits du terroir", "Spécialités régionales et produits traditionnels."),
    ("Produits artisanaux", "Articles fabriqués de manière artisanale."),
    ("Produits équitables", "Articles issus du commerce équitable."),
    ("Produits durables", "Articles respectueux de l'environnement."),
    ("Produits de fête", "Articles spéciaux pour les occasions festives."),
    ("Électronique", "Appareils électroniques, smartphones, ordinateurs, etc."),
    ("Jouets", "Jouets pour enfants de tous âges."),
    ("Vêtements", "Habillement pour hommes, femmes et enfants."),
    ("Chaussures", "Chaussures et accessoires de mode."),
    ("Accessoires", "Sacs, bijoux, montres et autres accessoires."),
    ("Mobilier", "Meubles et articles de décoration."),
    ("Électroménager", "Appareils électroménagers pour la maison."),
    ("Informatique", "Ordinateurs, périphériques et accessoires informatiques."),
    ("Téléphonie", "Smartphones, tablettes et accessoires mobiles."),
    ("Jeux vidéo", "Consoles, jeux et accessoires de gaming."),
    ("Livres", "Livres, magazines et produits culturels."),
    ("Musique", "Instruments de musique et accessoires."),
    ("Sport", "Équipements et accessoires sportifs."),
    ("Bricolage", "Outils et matériaux pour le bricolage."),
    ("Jardinage", "Plantes, outils et accessoires de jardin."),
    ("Auto-moto", "Pièces et accessoires pour véhicules."),
    ("Bien-être", "Produits pour le bien-être et la relaxation."),
    ("Fournitures de bureau", "Matériel et fournitures pour le bureau."),
    ("Cuisine", "Ustensiles et accessoires de cuisine."),
    ("Décoration", "Articles de décoration intérieure."),
    ("Luminaires", "Éclairage et accessoires d'éclairage."),
    ("Textiles", "Linge de maison et tissus."),
    ("Immobilier", "Trouvez et réalisez vos projets immobiliers en toute confiance."),
    ("Formation", "Développez vos compétences grâce à des formations adaptées."),
    ("Location", "Louez facilement logements, véhicules ou équipements selon vos besoins."),
    ("Voyage", "Accessoires et équipements de voyage."),
    ("Services", "Profitez de services pratiques comme livraison, chauffeur ou cours à domicile.");

